extends: airbnb-base
env:
  es6: true
  node: true
plugins: ['prettier']
parserOptions:
  # ecmaVersion: 8
  sourceType: module
globals:
  _: false
  sails: false
  Axios: false
  Capitalize: false
  Bcrypt: false
  Crypto: false
  Moment: false
  Schedule: false
  Raven: false
  ResponseHelper: false
  UUID: false
  #Services
  TokenService: false
  #Models
  User: false
  Vehicle: false
  Reservation: false
  Slot: false
rules:
  max-len:
    - 0
    - 200
    - 2
  no-console: error
  no-underscore-dangle: off
  comma-dangle: [error, always-multiline, { functions: never }]
  func-names: off
  camelcase: off
  consistent-return: off
  global-require: off
  arrow-parens: off
  object-curly-newline: off
  nonblock-statement-body-position: off
  curly: off
  implicit-arrow-linebreak: off
  spaced-comment: off
